### ISSUE TITLE
Configuration of data for Influx

### ISSUE THREAD

**Issue by worldpeace-germany** [worldpeace-germany/rctDataServer#2]
Currently a project internal CSV file controls what data is stored in Influx and what not. It can be changed but requires that the project gets compiled again. If demand is there a new method using a configuration file being project external is needed that a non-developer can change the behavior and that there is no need to recompile. Please leave comments if that is urgently needed.

**Comment by gt026328** [comment]
Hi, 
I'm a non-developer and like to have more instructions how to compile the project after changing the CSV file.
Thanks a lot

**Comment by gt026328** [comment]
Or much more better make the csv file as a config file with no need to compile entiere project. Just restart the Server. That would be great!

**Comment by worldpeace-germany** [comment]
Hello, thanks for the feedback. In general I agree the CSV file should be read from some location specified in the config file. Just a matter of time and priority. But back to your desire. May I ask what do you want to change in that file? If you are aware of new magic numbers, then it would be nice to share them that I can add them for everyone. To solve your problem with a work around please try the following:

1. rename the jar file to .zip (changing of file type)
2. Open the zip file and navigate to BOOT-INF --> classes --> here you see the csv
3. edit the csv and update the zip file (make sure that the zip file really contains the latest changes)
4. do not rename any file within the zip (probably obvious)
5. rename the file back from .zip to .jar

Does that work?

I will leave the request open since I should one day change reading the file.

**Comment by gt026328** [comment]
﻿Hey, thanks for sending this mail,
well first of all I'm running the actual Version on rctDataServer since 2 Weeks and still play around with the Data.
More Data to play with and understand if it makes sense to capture this for a period are the following M# 

CA6D6472;Daily haushold energy (Eload) [Wh];long;rctdb
E04C3900;Daily energy on AC output (Eac) [Wh];long;rctdb;
F79D41D9;Heat sink temperature [C];short;rctdb;
B84A38AB;Battery SoC target high;short;

From your Instruction below I understand that I have to "configure" the 
CSV file before the "initial installation" starts.
Now that I have a running system, will a second installation override some configs I did in the past?

 Thank you very much for this great Data-Collecting-Tool. 
I like it very much.

**Comment by worldpeace-germany** [comment]
Hi,

the first three items are already captured, no need for any change for that. 

You can change back and forth the different jar files without touching the config file. The config file will not be overwritten and it is being read only.

**Comment by worldpeace-germany** [comment]
With version 0.1.5. you can control the data being captured now with a configuration file. See updated documentation. Let me know if you have further questions or issues.
